package eco

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// Trimmed from a real Cargo.lock (version 4) written by cargo 1.89 for a
// two-member workspace; checksums removed.
const cargoLock = `# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "cc"
version = "1.4.6"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "getrandom"
version = "0.1.16"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "libc",
]

[[package]]
name = "getrandom"
version = "0.2.17"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "libc",
]

[[package]]
name = "helper"
version = "0.0.1"
dependencies = [
 "memchr",
]

[[package]]
name = "itoa"
version = "1.0.18"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "libc"
version = "0.2.189"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "memchr"
version = "2.8.3"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "my-app"
version = "0.1.0"
dependencies = [
 "cc",
 "itoa",
 "my-core",
 "rand 0.7.3",
 "rand 0.8.8",
 "serde_json",
]

[[package]]
name = "my-core"
version = "0.2.0"
dependencies = [
 "helper",
 "serde",
]

[[package]]
name = "rand"
version = "0.7.3"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "getrandom 0.1.16",
 "libc",
]

[[package]]
name = "rand"
version = "0.8.8"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "getrandom 0.2.17",
 "libc",
]

[[package]]
name = "serde"
version = "1.0.229"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "serde_json"
version = "1.0.151"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "itoa",
 "memchr",
 "serde",
]
`

func TestCargoWithMembers(t *testing.T) {
	members := []CargoMember{
		{Name: "my-app", DepKinds: map[string]string{"cc": "build", "itoa": "dev", "my_core": "", "rand": "", "serde_json": ""}},
		{Name: "my-core", DepKinds: map[string]string{"serde": "", "helper": ""}},
	}
	g, err := BuildCargo("Cargo.lock", []byte(cargoLock), members)
	if err != nil {
		t.Fatal(err)
	}
	tests := []struct {
		name string
		want []string
	}{
		{"serde", []string{"my-core@0.2.0 > serde@1.0.229", "my-app@0.1.0 > serde_json@1.0.151 > serde@1.0.229"}},
		{"memchr", []string{"my-core@0.2.0 > helper@0.0.1 > memchr@2.8.3", "my-app@0.1.0 > serde_json@1.0.151 > memchr@2.8.3"}},
		{"itoa", []string{"my-app@0.1.0 > itoa@1.0.18[dev]", "my-app@0.1.0 > serde_json@1.0.151 > itoa@1.0.18"}},
		{"cc", []string{"my-app@0.1.0 > cc@1.4.6[build]"}},
		{"serde-json", []string{"my-app@0.1.0 > serde_json@1.0.151"}},
		{"getrandom", []string{"my-app@0.1.0 > rand@0.7.3 > getrandom@0.1.16", "my-app@0.1.0 > rand@0.8.8 > getrandom@0.2.17"}},
		{"my-core", []string{"my-core@0.2.0"}},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := pathsOf(t, g, tt.name); !sameSet(got, tt.want) {
				t.Errorf("got  %q\nwant %q", got, tt.want)
			}
		})
	}
	if g.Nodes["helper 0.0.1"].Root {
		t.Error("path dependency helper should not be a root")
	}
}

func TestCargoWithoutMembers(t *testing.T) {
	g, err := BuildCargo("Cargo.lock", []byte(cargoLock), nil)
	if err != nil {
		t.Fatal(err)
	}
	// Without Cargo.toml the only local crate nothing depends on is my-app.
	var roots []string
	for _, id := range g.Roots() {
		roots = append(roots, g.Nodes[id].Name)
	}
	if strings.Join(roots, ",") != "my-app" {
		t.Errorf("roots = %v", roots)
	}
	if got := pathsOf(t, g, "serde"); !sameSet(got, []string{"my-app@0.1.0 > serde_json@1.0.151 > serde@1.0.229", "my-app@0.1.0 > my-core@0.2.0 > serde@1.0.229"}) {
		t.Errorf("got %q", got)
	}
}

func TestCargoSourceDisambiguation(t *testing.T) {
	lock := `version = 3

[[package]]
name = "app"
version = "0.1.0"
dependencies = [
 "foo 1.0.0 (git+https://github.com/x/foo?branch=main#abc123)",
]

[[package]]
name = "foo"
version = "1.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "foo"
version = "1.0.0"
source = "git+https://github.com/x/foo?branch=main#abc123"
`
	g, err := BuildCargo("Cargo.lock", []byte(lock), nil)
	if err != nil {
		t.Fatal(err)
	}
	edges := g.Edges["app 0.1.0"]
	if len(edges) != 1 || !strings.Contains(edges[0].To, "git+") {
		t.Errorf("edges = %+v", edges)
	}
}

func TestCargoV1RootTable(t *testing.T) {
	lock := `[root]
name = "old"
version = "0.1.0"
dependencies = [
 "libc 0.2.40 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "libc"
version = "0.2.40"
source = "registry+https://github.com/rust-lang/crates.io-index"

[metadata]
"checksum libc 0.2.40 (registry+https://github.com/rust-lang/crates.io-index)" = "abc"
`
	g, err := BuildCargo("Cargo.lock", []byte(lock), nil)
	if err != nil {
		t.Fatal(err)
	}
	if got := pathsOf(t, g, "libc"); !sameSet(got, []string{"old@0.1.0 > libc@0.2.40"}) {
		t.Errorf("got %q", got)
	}
}

func TestCargoErrors(t *testing.T) {
	_, err := BuildCargo("Cargo.lock", []byte("version = 4\n[[package]]\nname = \"x\nversion = \"1\"\n"), nil)
	if err == nil || !strings.Contains(err.Error(), "Cargo.lock: line 3") {
		t.Errorf("err = %v", err)
	}
	if _, err := BuildCargo("Cargo.lock", []byte("version = 4\n"), nil); err == nil {
		t.Error("expected error for lockfile without packages")
	}
}

func writeFiles(t *testing.T, dir string, files map[string]string) {
	t.Helper()
	for name, content := range files {
		p := filepath.Join(dir, filepath.FromSlash(name))
		if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(p, []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}
}

func TestCargoMembersFromManifests(t *testing.T) {
	dir := t.TempDir()
	writeFiles(t, dir, map[string]string{
		"Cargo.toml": `[workspace]
members = ["crates/*"]
exclude = ["crates/skipped"]
resolver = "2"

[workspace.dependencies]
serde = { version = "1.0.210", features = ["derive"] }
json = { package = "serde_json", version = "1" }
`,
		"crates/app/Cargo.toml": `[package]
name = "my-app"
version = "0.1.0"

[dependencies]
serde_json = "1.0.128"
rand07 = { package = "rand", version = "0.7" }
json.workspace = true

[dev-dependencies]
itoa = "1"
serde_json = "1"

[build-dependencies]
cc = "1.1"

[target.'cfg(windows)'.dev-dependencies]
winapi = "0.3"
`,
		"crates/core/Cargo.toml": `[package]
name = "my-core"
version.workspace = true

[dependencies]
serde.workspace = true
`,
		"crates/skipped/Cargo.toml": "[package]\nname = \"skipped\"\n",
		"crates/notacrate/README":   "x",
	})
	read := func(rel string) ([]byte, error) { return os.ReadFile(filepath.Join(dir, rel)) }
	glob := func(pattern string) ([]string, error) {
		matches, err := filepath.Glob(filepath.Join(dir, pattern))
		var rel []string
		for _, m := range matches {
			r, _ := filepath.Rel(dir, m)
			rel = append(rel, r)
		}
		return rel, err
	}
	members, warnings := CargoMembers(read, glob)
	if len(warnings) != 0 {
		t.Errorf("warnings: %v", warnings)
	}
	if len(members) != 2 || members[0].Name != "my-app" || members[1].Name != "my-core" {
		t.Fatalf("members = %+v", members)
	}
	want := map[string]string{"serde_json": "", "rand": "", "itoa": "dev", "cc": "build", "winapi": "dev"}
	for k, v := range want {
		if got, ok := members[0].DepKinds[k]; !ok || got != v {
			t.Errorf("my-app kind[%s] = %q, %v; want %q", k, got, ok, v)
		}
	}
	if _, ok := members[1].DepKinds["serde"]; !ok {
		t.Errorf("my-core kinds = %v", members[1].DepKinds)
	}
}

func TestCargoMembersBadManifest(t *testing.T) {
	read := func(rel string) ([]byte, error) {
		return []byte("[package]\nname = \"x\"\nedition = 2021-01-01\n"), nil
	}
	members, warnings := CargoMembers(read, filepath.Glob)
	if members != nil || len(warnings) != 1 || !strings.Contains(warnings[0], "line 3") {
		t.Errorf("members=%v warnings=%v", members, warnings)
	}
}
